language: node_js
node_js:
    - '12'
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
install:
  - npm install
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "dingzd1995"
  - git config user.email "dingzd1995@foxmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"` GMT +8:00 ."
  - git push --force --quiet "https://${travis}@${GH_REF}" master:master
branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/dingzd1995/dingzd1995.github.io.git
